### ISSUE TITLE
feat():  Add webserver archetype

### ISSUE THREAD

**Issue by scott-wyatt** [fabrix-app/fab-cli#1]
#### Feature Description
- When an app is generated, if a webserver is selected, it should merge it's archetype into the parent app and configure.

**Comment by jaumard** [comment]
#2 #3 are actually the same, in fact it should be generic enough to loop under spools and merge archetype, that will make easy the "add spool" command :)

**Comment by scott-wyatt** [comment]
You are probably right! :-)

**Comment by jaumard** [comment]
Fixed :)
